# Generated by Django 3.1.7 on 2021-05-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_add',
            field=models.BooleanField(default=False),
        ),
    ]
