# Generated by Django 3.1.7 on 2021-05-30 21:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='count'),
        ),
    ]
