# Generated by Django 3.1.7 on 2021-05-30 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210531_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='count'),
        ),
    ]
