# Generated by Django 3.1.7 on 2021-05-31 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20210531_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.CharField(max_length=2, verbose_name='count'),
        ),
    ]
