# Generated by Django 3.1.7 on 2021-05-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20210531_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.CharField(default=5000, max_length=100, verbose_name='total price'),
            preserve_default=False,
        ),
    ]
