# Generated by Django 3.1.7 on 2021-05-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user.account', '0003_auto_20210419_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
