# Generated by Django 3.1.7 on 2021-05-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user.account', '0007_auto_20210530_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='author',
            new_name='user',
        ),
    ]
