# Generated by Django 3.1.7 on 2021-03-29 16:27

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_images_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.category'),
        ),
    ]
