# Generated by Django 3.1.7 on 2021-03-29 16:29

from django.db import migrations
import django.db.models.deletion
import treewidget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210329_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=treewidget.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
