# Generated by Django 3.1.7 on 2021-03-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210330_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/noimage.png', null=True, upload_to='product_main'),
        ),
    ]
