# Generated by Django 3.1.7 on 2021-03-31 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210331_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='warranty',
            new_name='score',
        ),
    ]
