# Generated by Django 3.1.7 on 2021-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='club',
            field=models.CharField(default=2, max_length=255, verbose_name='club'),
            preserve_default=False,
        ),
    ]
