# Generated by Django 3.1.7 on 2021-04-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.FloatField(blank=True, max_length=50, verbose_name='value'),
        ),
    ]
